polls/urls.py
from django.urls import path
from . import views
app_name = 'polls'

urlpatterns = [
    path('',views.IndexView.as_view(),name='index'),
    path('<int:pk>/detail/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='votes'),
]

practice/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/',include('polls.urls')),
]

polls/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=255)
    pub_date = models.DateTimeField('Date Published',default=timezone.now())


    def __str__(self):
        return self.question_text

    def was_recently_published(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_recently_published.admin_order_field = 'pub_date'
    was_recently_published.boolean = True
    was_recently_published.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, related_name='choices', on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=255)
    count = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import redirect, get_object_or_404
from django.views import generic
from .models import Choice, Question
from django.urls import reverse


# Create your views here.


class IndexView(generic.ListView):
    context_object_name = 'questions_list'
    template_name = 'polls/index.html'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    if request.method == 'GET':
        return redirect(reverse('polls:detail', args=(question_id,)))
    choice = get_object_or_404(Choice, pk=request.POST.get('choice'))
    choice.count = choice.count + 1
    choice.save()
    return redirect(reverse('polls:results', args=(question_id,)))

templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

<form action="{% url 'polls:votes' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choices.all %}
    <input type="radio" name="choice" value="{{ choice.id}}" id="choice{{ choice.id }}">
    <label for="choice{{ choice.id }}">{{ choice.choice_text }}</label><br/>
{% endfor %}
<input type="submit" value="Save">
</form>

templates/polls/index.html
{% if questions_list %}
    <ul>
        {% for question in questions_list %}
            <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }} </a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>There are no polls.</p>
{% endif %}

templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choices.all %}
    <li>{{ choice }} -- {{ choice.count }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote Again</a>